# ==============================================================================
# CONFIGURACION DE LA BASE DE DATOS (MySQL)
# ==============================================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/habitalisDB?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345678}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================================================
# CONFIGURACION DE JPA / HIBERNATE
# ==============================================================================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

# ==============================================================================
# LOGGING
# ==============================================================================
logging.level.org.hibernate.orm.results=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ==============================================================================
# CONFIGURACION JACKSON (JSON)
# ==============================================================================
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# ==============================================================================
# ALMACENAMIENTO
# ==============================================================================
app.almacenamiento.raiz=${UPLOAD_DIR:C:/Users/sierr/Desktop/Habitalis/}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ==============================================================================
# INTEGRACIONES
# ==============================================================================
resend.api.key=${RESEND_API_KEY:re_ZWkoijQK_LQVmbDpZjs6eHMGnxSe6VQqN}
app.frontend.url=${APP_FRONTEND_URL:http://localhost:4200}